name: Issue Automation

on:
  issues:
    types: [opened, assigned, closed, reopened]

jobs:
  issue-opened:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ediazjz
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  issue-assigned:
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ediazjz
          column: In progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  issue-closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ediazjz
          column: Done
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  issue-reopened:
    runs-on: ubuntu-latest
    if: github.event.action == 'reopened'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ediazjz
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
